// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1E4nhl60-GHv_cllXEokMU4fuW5JcRXQ',
    appId: '1:710655165565:web:df346ee407344be7a71d14',
    messagingSenderId: '710655165565',
    projectId: 'bip-app-c0db6',
    authDomain: 'bip-app-c0db6.firebaseapp.com',
    storageBucket: 'bip-app-c0db6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeNxCrata_FwCMqQYMRYx9fGqmnGNUh20',
    appId: '1:710655165565:android:76abb0d20d2d22d8a71d14',
    messagingSenderId: '710655165565',
    projectId: 'bip-app-c0db6',
    storageBucket: 'bip-app-c0db6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrvqzGR-bizk8l4XMA6H4NDizVLrc9Xq8',
    appId: '1:710655165565:ios:5378a939861e5ab7a71d14',
    messagingSenderId: '710655165565',
    projectId: 'bip-app-c0db6',
    storageBucket: 'bip-app-c0db6.appspot.com',
    iosClientId: '710655165565-r5uggk6bs31riahvr7nu44jvmlmhdbng.apps.googleusercontent.com',
    iosBundleId: 'com.amingenieria.bip.bip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrvqzGR-bizk8l4XMA6H4NDizVLrc9Xq8',
    appId: '1:710655165565:ios:5378a939861e5ab7a71d14',
    messagingSenderId: '710655165565',
    projectId: 'bip-app-c0db6',
    storageBucket: 'bip-app-c0db6.appspot.com',
    iosClientId: '710655165565-r5uggk6bs31riahvr7nu44jvmlmhdbng.apps.googleusercontent.com',
    iosBundleId: 'com.amingenieria.bip.bip',
  );
}
